AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false
